/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.wicaku;

import javax.swing.UIManager;

/**
 *
 * @author wicaku
 */
public class frame extends javax.swing.JFrame {

    /**
     * Creates new form frame
     */
    public frame() {
        initComponents();
        this.setLocationRelativeTo(null); //center the frame on start
        this.setLookandFeel();
    }

    void setLookandFeel() {
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (Exception e) {
            System.out.println("Error setting native LAF: " + e);
        }

        /*try {
        UIManager.setLookAndFeel("com.sun.java.swing.plaf.gtk.GTKLookAndFeel");
        } catch (Exception e) {
        System.out.println("Error setting native LAF: " + e);
        }*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        intermezzo = new javax.swing.JLabel();
        SmartValuePanel = new javax.swing.JPanel();
        label5 = new javax.swing.JLabel();
        label187 = new javax.swing.JLabel();
        label188 = new javax.swing.JLabel();
        label197 = new javax.swing.JLabel();
        label198 = new javax.swing.JLabel();
        iSMART5 = new javax.swing.JTextField();
        iSMART187 = new javax.swing.JTextField();
        iSMART188 = new javax.swing.JTextField();
        iSMART197 = new javax.swing.JTextField();
        iSMART198 = new javax.swing.JTextField();
        SmartOptionalPanel = new javax.swing.JPanel();
        label10 = new javax.swing.JLabel();
        label200 = new javax.swing.JLabel();
        label201 = new javax.swing.JLabel();
        iSMART10 = new javax.swing.JTextField();
        iSMART200 = new javax.swing.JTextField();
        iSMART201 = new javax.swing.JTextField();
        oStatusBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        oResult = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("S.M.A.R.T Hardrive Checker");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(0, 0));
        setResizable(false);

        intermezzo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        intermezzo.setText("S.M.A.R.T stand for Self-Monitoring, Analysis and Reporting Technology");
        intermezzo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        SmartValuePanel.setBorder(javax.swing.BorderFactory.createTitledBorder("S.M.A.R.T Value"));
        SmartValuePanel.setToolTipText("Input Value Here");

        label5.setText("5");

        label187.setText("187");

        label188.setText("188");

        label197.setText("197");

        label198.setText("198");

        javax.swing.GroupLayout SmartValuePanelLayout = new javax.swing.GroupLayout(SmartValuePanel);
        SmartValuePanel.setLayout(SmartValuePanelLayout);
        SmartValuePanelLayout.setHorizontalGroup(
            SmartValuePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SmartValuePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SmartValuePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(label198)
                    .addComponent(label197)
                    .addComponent(label188)
                    .addComponent(label187)
                    .addComponent(label5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SmartValuePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(iSMART5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(SmartValuePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(iSMART187, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(iSMART188, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(iSMART197, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(iSMART198, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        SmartValuePanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {label187, label188, label197, label198, label5});

        SmartValuePanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {iSMART187, iSMART188, iSMART197, iSMART198, iSMART5});

        SmartValuePanelLayout.setVerticalGroup(
            SmartValuePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SmartValuePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(SmartValuePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(iSMART5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SmartValuePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(iSMART187, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label187))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SmartValuePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(iSMART188, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label188))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SmartValuePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(iSMART197, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label197))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SmartValuePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(iSMART198, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label198)))
        );

        SmartValuePanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {label187, label188, label197, label198, label5});

        SmartValuePanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {iSMART187, iSMART188, iSMART197, iSMART198, iSMART5});

        SmartOptionalPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Optional Value"));
        SmartOptionalPanel.setToolTipText("Input Value Here");

        label10.setText("10");

        label200.setText("200");

        label201.setText("201");

        javax.swing.GroupLayout SmartOptionalPanelLayout = new javax.swing.GroupLayout(SmartOptionalPanel);
        SmartOptionalPanel.setLayout(SmartOptionalPanelLayout);
        SmartOptionalPanelLayout.setHorizontalGroup(
            SmartOptionalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SmartOptionalPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SmartOptionalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(label201)
                    .addComponent(label200)
                    .addComponent(label10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SmartOptionalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(iSMART10, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(SmartOptionalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(iSMART200, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(iSMART201, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        SmartOptionalPanelLayout.setVerticalGroup(
            SmartOptionalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SmartOptionalPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SmartOptionalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(iSMART10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SmartOptionalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(iSMART200, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label200))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SmartOptionalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(iSMART201, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label201))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        oStatusBtn.setText("Check Status");
        oStatusBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oStatusBtnActionPerformed(evt);
            }
        });

        oResult.setEditable(false);
        oResult.setColumns(20);
        oResult.setRows(5);
        jScrollPane1.setViewportView(oResult);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(oStatusBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(intermezzo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(SmartValuePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(SmartOptionalPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(intermezzo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(SmartValuePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SmartOptionalPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(oStatusBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void oStatusBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oStatusBtnActionPerformed
        // TODO add your handling code here:
        main app = new main();

        //System.out.println(iSMART5.getText().isEmpty());
        if (iSMART5.getText().isEmpty()
                && iSMART10.getText().isEmpty()
                && iSMART187.getText().isEmpty()
                && iSMART188.getText().isEmpty()
                && iSMART197.getText().isEmpty()
                && iSMART198.getText().isEmpty()
                && iSMART200.getText().isEmpty()
                && iSMART201.getText().isEmpty()) {
            oResult.append(app.mCheckStatus());
        } else if (iSMART10.getText().isEmpty()
                && iSMART200.getText().isEmpty()
                && iSMART201.getText().isEmpty()) {
            oResult.append(app.mCheckStatus(
                    Double.valueOf(iSMART5.getText()),
                    Double.valueOf(iSMART187.getText()),
                    Double.valueOf(iSMART188.getText()),
                    Double.valueOf(iSMART197.getText()),
                    Double.valueOf(iSMART198.getText())));
        } else {
            oResult.append(app.mCheckStatus(
                    Double.valueOf(iSMART5.getText()),
                    Double.valueOf(iSMART10.getText()),
                    Double.valueOf(iSMART187.getText()),
                    Double.valueOf(iSMART188.getText()),
                    Double.valueOf(iSMART197.getText()),
                    Double.valueOf(iSMART198.getText()),
                    Double.valueOf(iSMART200.getText()),
                    Double.valueOf(iSMART201.getText())));
        }
    }//GEN-LAST:event_oStatusBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel SmartOptionalPanel;
    private javax.swing.JPanel SmartValuePanel;
    private javax.swing.JTextField iSMART10;
    private javax.swing.JTextField iSMART187;
    private javax.swing.JTextField iSMART188;
    private javax.swing.JTextField iSMART197;
    private javax.swing.JTextField iSMART198;
    private javax.swing.JTextField iSMART200;
    private javax.swing.JTextField iSMART201;
    private javax.swing.JTextField iSMART5;
    private javax.swing.JLabel intermezzo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label10;
    private javax.swing.JLabel label187;
    private javax.swing.JLabel label188;
    private javax.swing.JLabel label197;
    private javax.swing.JLabel label198;
    private javax.swing.JLabel label200;
    private javax.swing.JLabel label201;
    private javax.swing.JLabel label5;
    private javax.swing.JTextArea oResult;
    private javax.swing.JButton oStatusBtn;
    // End of variables declaration//GEN-END:variables
}
